name: "noaa_weather_dbt"
version: "1.0.0"
config-version: 2

profile: "noaa_duckdb"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  reference_path: "../data/reference"

models:
  noaa_weather_dbt:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: incremental
      +unique_key: ["station_id", "date", "element"]
